eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
       endpont:
         uri: http://PAYMENT-SERVICE-API/payment/doPayment
  order-service:
    endpoints:
      endpont:
        uri: http://ORDER-SERVICE-API/order/bookOrder    
